#!/bin/bash

# Charitap Extension Testing Script
# This will help you verify the extension is working

echo "════════════════════════════════════════════════"
echo "  CHARITAP EXTENSION TESTING GUIDE"
echo "════════════════════════════════════════════════"
echo ""

echo "✅ STEP 1: Restart Frontend (REQUIRED!)"
echo "You updated .env file with extension ID"
echo "Frontend must be restarted to pick up changes"
echo ""
echo "Run these commands in a NEW terminal:"
echo "  cd /Users/himanshunimonkar/Downloads/Charitap/Charitap-chrome-extension"
echo "  pkill -f 'react-scripts start'"
echo "  npm start"
echo ""
echo "Wait for: 'webpack compiled successfully'"
echo ""
read -p "Press ENTER once frontend restarted..."

echo ""
echo "✅ STEP 2: Sign In to Charitap"
echo ""
echo "1. Open browser and go to: http://localhost:3000"
echo "2. Click 'Sign In' button"
echo "3. Use your email/password OR Google Sign-In"
echo "4. You should see your dashboard"
echo ""
echo "IMPORTANT: Extension ONLY works when logged in!"
echo ""
read -p "Press ENTER once you're signed in..."

echo ""
echo "✅ STEP 3: Verify Extension Received User Data"
echo ""
echo "1. Open Browser DevTools (F12)"
echo "2. Go to Console tab"
echo "3. Look for these messages:"
echo "   - 'Website: User data successfully sent to extension'"
echo "   - 'Stored Email: your@email.com'"
echo "   - 'Stored Token: Present'"
echo ""
echo "If you DON'T see these messages:"
echo "  - Frontend might not be restarted"
echo "  - Extension ID might be wrong"
echo "  - Extension might not be loaded"
echo ""
read -p "Press ENTER if you see success messages..."

echo ""
echo "✅ STEP 4: Test on Amazon"
echo ""
echo "1. Go to Amazon.com"
echo "2. Add ANY item to cart"
echo "3. Go to checkout page"
echo "   URL should contain: /checkout, /payment, or /buy"
echo ""
echo "4. Open Browser Console (F12)"
echo "5. Look for Charitap logs:"
echo "   [Charitap] Content script loaded"
echo "   [Charitap] User data from storage: {userId: ..., userEmail: ...}"
echo "   [Charitap] User logged in, initializing..."
echo "   [Charitap] Platform detected: amazon"
echo "   [Charitap] Checkout page detected"
echo "   [Charitap] Showing widget..."
echo ""
echo "6. Widget should appear in BOTTOM-RIGHT corner"
echo "   - Green circle with Charitap logo"
echo "   - Shows round-up amount"
echo "   - Has ✓ button"
echo ""
read -p "Press ENTER when on Amazon checkout page..."

echo ""
echo "✅ STEP 5: Test Donation Flow"
echo ""
echo "1. Click the green ✓ (checkmark) button"
echo "2. You should see:"
echo "   - Confetti animation 🎉"
echo "   - Success popup with amount"
echo "   - Auto-closes after 3 seconds"
echo ""
echo "3. Check browser console for:"
echo "   [Charitap] Processing donation"
echo "   [Charitap] Response from background: {success: true}"
echo ""
read -p "Press ENTER once you tested..."

echo ""
echo "════════════════════════════════════════════════"
echo "  TROUBLESHOOTING"
echo "════════════════════════════════════════════════"
echo ""

echo "🔍 ISSUE: 'No user data found in storage'"
echo "   FIX: You need to sign in to http://localhost:3000 first!"
echo ""

echo "🔍 ISSUE: No '[Charitap]' logs in console"
echo "   FIX: Extension not loaded or content script blocked"
echo "   1. Go to chrome://extensions/"
echo "   2. Verify extension is enabled"
echo "   3. Check for errors"
echo "   4. Click Reload button"
echo ""

echo "🔍 ISSUE: 'Failed to add donation'"
echo "   FIX: Backend not running"
echo "   Run: node backend/server.js"
echo ""

echo "🔍 ISSUE: Widget doesn't appear"
echo "   CHECKS:"
echo "   1. Are you signed in? (http://localhost:3000)"
echo "   2. Are you on checkout page? (not product page)"
echo "   3. Is extension enabled? (chrome://extensions/)"
echo "   4. Does console show '[Charitap]' logs?"
echo ""

echo "════════════════════════════════════════════════"
echo "  MANUAL DIAGNOSTIC"
echo "════════════════════════════════════════════════"
echo ""
echo "Run this in Browser Console on Amazon page:"
echo ""
echo "chrome.storage.local.get(['userId', 'userEmail', 'userToken'], (data) => {"
echo "  console.log('User logged in?', data.userEmail ? 'YES' : 'NO');"
echo "  console.log('Data:', data);"
echo "});"
echo ""
echo "If returns empty/null → Sign in to website first!"
echo ""

echo "════════════════════════════════════════════════"
echo "  Quick Checklist"
echo "════════════════════════════════════════════════"
echo ""
echo "[ ] Frontend restarted after .env update"
echo "[ ] Signed in to http://localhost:3000"
echo "[ ] Backend running on port 3001"
echo "[ ] Extension enabled in chrome://extensions/"
echo "[ ] On Amazon CHECKOUT page (not product)"
echo "[ ] Browser console shows '[Charitap]' logs"
echo ""

echo "════════════════════════════════════════════════"
echo "  All Done!"
echo "════════════════════════════════════════════════"
